name: Daily Discord Post

on:
  schedule:
    - cron: '*/1 * * * *'  # TEST MODE: every 2 minutes
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send webhook
        run: |
          content=$(cat message.txt)

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"$content\"}" \
          ${{ secrets.WEBHOOK_URL }}
